---
services:
  loki:
    image: docker.io/grafana/loki:3.6.4
    restart: unless-stopped
    command: "-config.file=/etc/loki/config.yaml"
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki:rw
      - ./config/config.yaml:/etc/loki/config.yaml:ro

volumes:
  loki_data:
    driver: local
