services:
  alloy:
    image: docker.io/grafana/alloy:v1.12.2
    restart: unless-stopped
    ports:
      - "12345:12345"
    volumes:
      - alloy_data:/alloy/data
      - ./config/config.alloy:/etc/alloy/config.alloy:ro
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /run:/run:ro
      - /var/log:/var/log:ro
      - /var/lib/docker/:/var/lib/docker/:ro
      - /run/udev/data:/run/udev/data:ro

volumes:
  alloy_data:
    driver: local
