---
services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    logging:
      driver: loki
      options:
        loki-url: "https://loki.home.lurking.site/loki/api/v1/push"
        loki-retries: 2
        loki-timeout: 1s
        loki-max-backoff: 800ms
        keep-file: "true"
        mode: non-blocking
    environment:
      - BIND9_USER=root
      - TZ=Australia/Brisbane
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/etc/bind/
      - ./cache:/var/cache/bind
      - ./lib:/var/lib/bind
    restart: unless-stopped