acl internal {
    172.20.0.0/16;
};

options {
    forwarders {
        1.1.1.1;
        8.8.8.8;
    };
    allow-query { internal; };
};

zone "lurking.site" {
    type master;
    file "/var/lib/bind/lurking-site.zone";
};